### ISSUE TITLE
Unable to pass options to Ink render() command

### ISSUE THREAD

**Issue by kellerj** [vadimdemedes/pastel#35] opened 2020-08-16 16:53 UTC
It would be nice if there was a mechanism to configure options to be passed into the render() method called in boot.js.  There are a couple options there which are useful when troubleshooting (and perhaps for more advanced use cases I don't have a need for).

It seems that it should be easy enough to include the props in the call, I just don't know what the best model for passing them in would be for this tool's design.  (pastel.config.js - taking a cue from Next.js?)

I wouldn't mind working on it if I have an idea what solution you would find acceptable.

**Comment by vadimdemedes** [comment] 2023-05-24 09:27
Agree, it would be nice to have. Going to close this as a duplicate of #43 👍

**Closed by vadimdemedes** 2023-05-24 09:27 UTC
